version: '3.8'

services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    command: ["odoo", "--config=/etc/odoo/odoo.conf"]
    networks:
      - odoo-network
      
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_odoo_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - odoo-network

networks:
  odoo-network:
    name: odoo-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

secrets:
  postgresql_password:
    file: odoo_pg_pass
